import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadTenant, type TenantConfig } from "@fetolsa/tenant-loader/loader";
import { TenantConfigSchema } from "@fetolsa/tenant-loader";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const TENANTS_DIR = join(REPO_ROOT, "tenants");

export interface InjectOptions {
  tenantCode: string;
  appKind: "customer" | "rider";
}

function tokenEnvVar(tenantCode: string): string {
  return `${tenantCode.toUpperCase().replace(/-/g, "_")}_API_TOKEN`;
}

function readApiToken(tenantCode: string): string {
  const varName = tokenEnvVar(tenantCode);
  const val = process.env[varName];
  if (!val || val.startsWith("<")) {
    throw new Error(
      `Missing env var: ${varName}\n` +
        `The mobile app needs a Frappe API token to fetch menu/branches.\n` +
        `Add to .env at repo root:  ${varName}=<api_key>:<api_secret>\n` +
        `See .env.example for details.`,
    );
  }
  if (!val.includes(":")) {
    throw new Error(`${varName} format invalid. Expected: api_key:api_secret`);
  }
  return val;
}

export function injectTenantConfig({ tenantCode, appKind }: InjectOptions): TenantConfig {
  const config = loadTenant(tenantCode, TENANTS_DIR);
  const apiToken = readApiToken(tenantCode);

  const appDir = join(REPO_ROOT, "apps", appKind);
  if (!existsSync(appDir)) {
    throw new Error(`App directory not found: ${appDir}`);
  }

  // 1. Write tenant.generated.ts (config + runtime apiToken from .env)
  const generatedPath = join(appDir, "src", "tenant.generated.ts");
  const runtimeConfig = { ...config, apiToken };
  const tsContent = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/inject-config.ts.
 * DO NOT EDIT BY HAND - changes will be overwritten on next build.
 *
 * Tenant: ${config.code} (${config.displayName})
 * App:    ${appKind}
 * Built:  ${new Date().toISOString()}
 *
 * apiToken is loaded from .env at build time (env var: ${tokenEnvVar(tenantCode)})
 */
import type { RuntimeTenantConfig } from "@fetolsa/tenant-loader";

export const tenant: RuntimeTenantConfig = ${JSON.stringify(runtimeConfig, null, 2)};
`;
  writeFileSync(generatedPath, tsContent, "utf-8");
  console.log(`  Wrote ${generatedPath.replace(REPO_ROOT, "")}`);

  // 2. Copy branded assets to android resource paths
  const assetsDir = join(REPO_ROOT, "tenants", tenantCode, "assets");
  const required = ["icon.png", "adaptive-fg.png", "adaptive-bg.png", "splash.png"];
  for (const file of required) {
    const src = join(assetsDir, file);
    if (!existsSync(src)) {
      throw new Error(`Required asset missing: ${src}`);
    }
  }

  const resourcesDir = join(appDir, "resources");
  if (!existsSync(resourcesDir)) mkdirSync(resourcesDir, { recursive: true });
  copyFileSync(join(assetsDir, "icon.png"), join(resourcesDir, "icon.png"));
  copyFileSync(join(assetsDir, "adaptive-fg.png"), join(resourcesDir, "icon-foreground.png"));
  copyFileSync(join(assetsDir, "adaptive-bg.png"), join(resourcesDir, "icon-background.png"));
  copyFileSync(join(assetsDir, "splash.png"), join(resourcesDir, "splash.png"));
  console.log(`  Copied 4 assets to apps/${appKind}/resources/`);

  // 3. Copy google-services.json if present
  const gservices = join(REPO_ROOT, "tenants", tenantCode, "google-services.json");
  if (existsSync(gservices)) {
    const dest = join(appDir, "android", "app", "google-services.json");
    if (!existsSync(dirname(dest))) mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(gservices, dest);
    console.log(`  Copied google-services.json`);
  } else {
    console.log(`  (no google-services.json for ${tenantCode} - skipping)`);
  }

  return config;
}

if (process.argv[1] && process.argv[1].endsWith("inject-config.ts")) {
  const [, , tenantCode, appKind] = process.argv;
  if (!tenantCode || !appKind) {
    console.error("Usage: inject-config.ts <tenant-code> <customer|rider>");
    process.exit(1);
  }
  if (appKind !== "customer" && appKind !== "rider") {
    console.error(`Invalid app kind: ${appKind}`);
    process.exit(1);
  }
  injectTenantConfig({ tenantCode, appKind });
  console.log("Done.");
}