import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadTenant, type TenantConfig } from "@fetolsa/tenant-loader/loader";
import { TenantConfigSchema } from "@fetolsa/tenant-loader";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const TENANTS_DIR = join(REPO_ROOT, "tenants");

export interface InjectOptions {
  tenantCode: string;
  appKind: "customer" | "rider";
}

export function injectTenantConfig({ tenantCode, appKind }: InjectOptions): TenantConfig {
  const config = loadTenant(tenantCode, TENANTS_DIR);

  const appDir = join(REPO_ROOT, "apps", appKind);
  if (!existsSync(appDir)) {
    throw new Error(`App directory not found: ${appDir}`);
  }

  // 1. Write tenant.generated.ts
  const generatedPath = join(appDir, "src", "tenant.generated.ts");
  const tsContent = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-tenant.ts.
 * DO NOT EDIT BY HAND - changes will be overwritten on next build.
 *
 * Tenant: ${config.code} (${config.displayName})
 * App:    ${appKind}
 * Built:  ${new Date().toISOString()}
 */
import type { TenantConfig } from "@fetolsa/tenant-loader";

export const tenant: TenantConfig = ${JSON.stringify(config, null, 2)};
`;
  writeFileSync(generatedPath, tsContent, "utf-8");
  console.log(`  Wrote ${generatedPath.replace(REPO_ROOT, "")}`);

  // 2. Copy branded assets to android resource paths
  const assetsDir = join(REPO_ROOT, "tenants", tenantCode, "assets");
  const required = ["icon.png", "adaptive-fg.png", "adaptive-bg.png", "splash.png"];
  for (const file of required) {
    const src = join(assetsDir, file);
    if (!existsSync(src)) {
      throw new Error(`Required asset missing: ${src}`);
    }
  }

  // Capacitor's @capacitor/assets tool expects a "resources" folder at the app root
  const resourcesDir = join(appDir, "resources");
  if (!existsSync(resourcesDir)) mkdirSync(resourcesDir, { recursive: true });
  copyFileSync(join(assetsDir, "icon.png"), join(resourcesDir, "icon.png"));
  copyFileSync(join(assetsDir, "adaptive-fg.png"), join(resourcesDir, "icon-foreground.png"));
  copyFileSync(join(assetsDir, "adaptive-bg.png"), join(resourcesDir, "icon-background.png"));
  copyFileSync(join(assetsDir, "splash.png"), join(resourcesDir, "splash.png"));
  console.log(`  Copied 4 assets to apps/${appKind}/resources/`);

  // 3. Copy google-services.json if present (gitignored, supplied at build time)
  const gservices = join(REPO_ROOT, "tenants", tenantCode, "google-services.json");
  if (existsSync(gservices)) {
    const dest = join(appDir, "android", "app", "google-services.json");
    if (!existsSync(dirname(dest))) mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(gservices, dest);
    console.log(`  Copied google-services.json`);
  } else {
    console.log(`  (no google-services.json for ${tenantCode} - skipping)`);
  }

  return config;
}

// Run as CLI: tsx scripts/inject-config.ts <tenant> <app>
if (process.argv[1] && process.argv[1].endsWith("inject-config.ts")) {
  const [, , tenantCode, appKind] = process.argv;
  if (!tenantCode || !appKind) {
    console.error("Usage: inject-config.ts <tenant-code> <customer|rider>");
    process.exit(1);
  }
  if (appKind !== "customer" && appKind !== "rider") {
    console.error(`Invalid app kind: ${appKind}`);
    process.exit(1);
  }
  injectTenantConfig({ tenantCode, appKind });
  console.log("Done.");
}